### ISSUE TITLE
Appropriate Home For `conventional-commits-detector`

### ISSUE THREAD

**Issue by hutson** [conventional-changelog/meta#1]
I am looking to do some updates on `conventional-commits-detector`, and I thought that it probably needs a new home.

I was thinking of migrating it into the `conventional-changelog` mono-repository to make maintenance easier, because the changelog presets we maintain are over there, and there is a one-to-one correlation between detected commit conventions and preset packages.

However, it's not really specific to our mission of creating conventional changelogs.

@conventional-changelog/committee what are y'alls thoughts on this?

**Comment by zeke** [comment]
I'm not familiar with this package, but given the name it seems @conventional-commits would be a great home for it.

**Comment by damianopetrungaro** [comment]
It looks really outdated actually.
Is someone still using it?

**Comment by hutson** [comment]
@damianopetrungaro a list of dependents is listed here - https://www.npmjs.com/package/conventional-commits-detector (On the _Dependents_ page).

It's used by [Renovate](http://renovatebot.com/) and a few release tools (two of which I maintain).

**Comment by hutson** [comment]
I have released version 1.0.0 of `conventional-commits-detector` as per - conventional-changelog/conventional-commits-detector/issues/3

For now I guess I will just keep the package under the `conventional-changelog` org (though I am still open to the idea of moving it to the `conventional-commits` org if others believe it would be more appropriate to belong there.)
